[package]
name = "evergreen_utility_ai_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
bevy_macro_utils = "0.15"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = "2.0.98"
